### ISSUE TITLE
get subject is slow

### ISSUE THREAD

**Issue by khamael** [mint-labs/mintlabs#31]
the get_subject and then the parameters of the API is kinda slow. where's the bottleneck?

**Comment by alvaroabascar** [comment]
get_subject was requesting each time all the list of subjects and metadata, in order to check the existence of the subject and find the id. I've added a cache so now it only does a request the first time get_subject is called. The cache can be disabled with `get_subject("subj_name", cache=False)`

for parameters:
subject.parameters does the request to the server each time and that's slow. It's intended, since the parameters could be changed in any moment.
I've implemented an endpoint `subject.get_parameters(cache=True)` which uses a cache by default. If you retrieve the parameters several times for one subject, you can use this method to save time.

**Comment by khamael** [comment]
which version is this?
TypeError: get_subject() got an unexpected keyword argument 'cache'

**Comment by alvaroabascar** [comment]
works fine for me, at least the last version. I can't upload it to pypi for some reason, but you can install through `sudo python3 setup.py install`

**Comment by alvaroabascar** [comment]
Try now
